# frozen_string_literal: true

require "thor"
require "terminal-table"

module RedSeed
  # CLI defines the commands and user interface for the RedSeed tool
  class CLI < Thor
    desc "analyze NEIGHBORHOOD", "Calculate food security score for a given neighborhood"
    def analyze(neighborhood)
      result = perform_analysis(neighborhood)
      return unless result

      display_results(result)
    end

    desc "export NEIGHBORHOOD", "Export analysis results to a markdown file in reports/"
    def export(neighborhood)
      result = perform_analysis(neighborhood)
      return unless result

      dirname = "reports"
      Dir.mkdir(dirname) unless File.exist?(dirname)

      filename = "#{dirname}/#{neighborhood.downcase.tr(' ', '_')}_analysis.md"
      File.write(filename, generate_markdown(result))
      say "Report exported successfully to #{filename}", :green
    end

    private

    def perform_analysis(neighborhood)
      say "Fetching data from Vancouver Open Data...", :yellow
      data = DataFetcher.fetch_all
      analyzer = Analyzer.new(data)
      result = analyzer.analyze_neighborhood(neighborhood)

      if result[:assets].empty?
        say "No data found for neighborhood: #{neighborhood}", :red
        say "Available neighborhoods include: #{analyzer.neighborhoods.first(10).join(', ')}...", :cyan
        return nil
      end
      result
    rescue StandardError => e
      say "Error: #{e.message}", :red
      nil
    end

    def display_results(result)
      table = ::Terminal::Table.new do |t|
        t.title = "RedSeed Analysis: #{result[:neighborhood]}"
        t.headings = ["Asset Name", "Type", "Points", "Recommendation"]
        add_asset_rows(t, result[:assets])
        t.add_separator
        t.add_row [{ value: "Total Score: #{result[:score]}", colspan: 4, alignment: :center }]
      end
      puts table
      check_low_score(result[:score])
    end

    def add_asset_rows(table, assets)
      assets.each do |asset|
        name = asset["program_name"] || asset["name"] || "Unknown"
        points = Analyzer::SCORING_RULES[asset["asset_type"]] || 0
        rec = points < 5 ? "Potential site for new community garden" : "N/A"
        table.add_row [name, asset["asset_type"], points, rec]
      end
    end

    def check_low_score(score)
      return unless score < 5

      say "\nNote: This neighborhood has a low food security score. " \
          "Consider advocating for more programs!", :magenta
    end

    def generate_markdown(result)
      lines = ["# RedSeed Analysis: #{result[:neighborhood]}", ""]
      lines << "| Asset Name | Type | Points | Recommendation |"
      lines << "|------------|------|--------|----------------|"
      result[:assets].each do |asset|
        lines << asset_md_row(asset)
      end
      lines << ""
      lines << "**Total Score: #{result[:score]}**"
      lines << ""
      lines << "_Generated by RedSeed CLI Tool_"
      lines.join("\n")
    end

    def asset_md_row(asset)
      name = asset["program_name"] || asset["name"] || "Unknown"
      points = Analyzer::SCORING_RULES[asset["asset_type"]] || 0
      rec = points < 5 ? "Potential site for new community garden" : "N/A"
      "| #{name} | #{asset['asset_type']} | #{points} | #{rec} |"
    end
  end
end
