require 'thor'
require 'terminal-table'

module RedSeed
  class CLI < Thor
    desc "analyze NEIGHBORHOOD", "Calculate food security score for a given neighborhood"
    def analyze(neighborhood)
      result = perform_analysis(neighborhood)
      return unless result
      display_results(result)
    end

    desc "export NEIGHBORHOOD", "Export analysis results to a markdown file in reports/"
    def export(neighborhood)
      result = perform_analysis(neighborhood)
      return unless result

      dirname = "reports"
      Dir.mkdir(dirname) unless File.exist?(dirname)
      
      filename = "#{dirname}/#{neighborhood.downcase.gsub(' ', '_')}_analysis.md"
      content = generate_markdown(result)
      
      File.write(filename, content)
      say "Report exported successfully to #{filename}", :green
    end

    private

    def perform_analysis(neighborhood)
      say "Fetching data from Vancouver Open Data...", :yellow
      data = DataFetcher.fetch_all
      analyzer = Analyzer.new(data)
      result = analyzer.analyze_neighborhood(neighborhood)

      if result[:assets].empty?
        say "No data found for neighborhood: #{neighborhood}", :red
        say "Available neighborhoods include: #{analyzer.neighborhoods.first(10).join(', ')}...", :cyan
        return nil
      end
      result
    rescue => e
      say "Error: #{e.message}", :red
      nil
    end

    def display_results(result)
      table = ::Terminal::Table.new do |t|
        t.title = "RedSeed Analysis: #{result[:neighborhood]}"
        t.headings = ['Asset Name', 'Type', 'Points', 'Recommendation']
        
        result[:assets].each do |asset|
          # Fields vary between datasets: programs use program_name, gardens use name
          name = asset["program_name"] || asset["name"] || "Unknown"
          points = Analyzer::SCORING_RULES[asset["asset_type"]] || 0
          recommendation = points < 5 ? "Potential site for new community garden" : "N/A"
          
          t.add_row [
            name,
            asset["asset_type"],
            points,
            recommendation
          ]
        end
        
        t.add_separator
        t.add_row [{value: "Total Score: #{result[:score]}", colspan: 4, alignment: :center}]
      end

      puts table
      
      if result[:score] < 5
        say "\nNote: This neighborhood has a low food security score. Consider advocating for more programs!", :magenta
      end
    end

    def generate_markdown(result)
      lines = []
      lines << "# RedSeed Analysis: #{result[:neighborhood]}"
      lines << ""
      lines << "| Asset Name | Type | Points | Recommendation |"
      lines << "|------------|------|--------|----------------|"
      
      result[:assets].each do |asset|
        name = asset["program_name"] || asset["name"] || "Unknown"
        points = Analyzer::SCORING_RULES[asset["asset_type"]] || 0
        recommendation = points < 5 ? "Potential site for new community garden" : "N/A"
        lines << "| #{name} | #{asset['asset_type']} | #{points} | #{recommendation} |"
      end
      
      lines << ""
      lines << "**Total Score: #{result[:score]}**"
      lines << ""
      lines << "_Generated by RedSeed CLI Tool_"
      lines.join("\n")
    end
  end
end
