# frozen_string_literal: true

module RedSeed
  # ReportGenerator handles formatting analysis results into Markdown
  module ReportGenerator
    def self.generate_markdown(result)
      lines = ["# RedSeed Analysis: #{result[:neighborhood]}", ""]
      lines << "| Asset Name | Type | Points | Recommendation |"
      lines << "|------------|------|--------|----------------|"
      result[:assets].each do |asset|
        lines << asset_md_row(asset)
      end
      lines << ""
      lines << "**Total Score: #{result[:score]}**"
      lines << ""
      lines << "_Generated by RedSeed CLI Tool_"
      lines.join("\n")
    end

    def self.asset_md_row(asset)
      name = asset["program_name"] || asset["name"] || "Unknown"
      points = Analyzer::SCORING_RULES[asset["asset_type"]] || 0
      rec = points < 5 ? "Potential site for new community garden" : "N/A"
      "| #{name} | #{asset['asset_type']} | #{points} | #{rec} |"
    end
  end
end
